# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Less Player Desktop

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
